.\" Copyright (c) 2024 Alexander Möller <alexander.moeller@detmold.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 14 2024 $
.Dt TOCSIN 1
.Os
.Sh NAME
.Nm tocsin
.Nd Script to detect bit rot
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
.Nm
is a script to detect bit rot by checking if a file changed without a change in
its modification date.
.Pp
Enter the directory to check and invoke the script.
.Nm
will start digging through the directory structure recursively indexing
all files found. The index is stored in a `.tocsin.db` file which is an SQLite
3 database.
.Pp
Next time
.Nm
is run it will add new files and update the index for files with a changed
modification date. Most importantly however, it will report all errors, e.g.
files that changed on the drive but still have the same modification date.
.Pp
All paths stored in `.tocsin.db` are relative, so it's safe to rescan a folder
after moving it to another drive. Just remember to move it in a way that doesn't
touch modification dates. Otherwise the checksum database is useless.
.Sh AUTHOR
.Nm
is a fork by
.An Alexander Möller Aq Mt alexander.moeller@detmold.com
of bitrot by
.An Łukasz Langa Aq Mt lukasz@langa.pl .
